//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseRentManagementSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Database1Entities5 : DbContext
    {
        public Database1Entities5()
            : base("name=Database1Entities5")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BookStatu> BookStatus { get; set; }
        public virtual DbSet<Property_Images> Property_Images { get; set; }
        public virtual DbSet<PropertyTable> PropertyTables { get; set; }
        public virtual DbSet<RegisterCustomer> RegisterCustomers { get; set; }
        public virtual DbSet<RegisterUser> RegisterUsers { get; set; }
    }
}
